name: Go

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        docker pull cowens09/hexdump:1.1.0
        docker save cowens09/hexdump:1.1.0 | gzip > cowens09_hexdump_1.1.0.tgz
    - name: 'Upload Artifact'
    - uses: actions/upload-artifact@v2
      with:
        name: cowens09_hexdump_1.1.0
        path: cowens09_hexdump_1.1.0.tgz
        retention-days: 2
